# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/guill/Desktop/Practica7.xpr/Practica7/Practica7.cache/wt [current_project]
set_property parent.project_path C:/Users/guill/Desktop/Practica7.xpr/Practica7/Practica7.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib {
  C:/Users/guill/Desktop/Practica7.xpr/Practica7/Practica7.srcs/sources_1/imports/new/registro_srl.vhd
  C:/Users/guill/Desktop/Practica7.xpr/Practica7/Practica7.srcs/sources_1/imports/new/half_period.vhd
  C:/Users/guill/Desktop/Practica7.xpr/Practica7/Practica7.srcs/sources_1/imports/Martes12/caca/detector_flancos.vhd
  C:/Users/guill/Desktop/Practica7.xpr/Practica7/Practica7.srcs/sources_1/imports/new/contador_8_bits.vhd
  C:/Users/guill/Desktop/Practica7.xpr/Practica7/Practica7.srcs/sources_1/imports/new/unidad_operativa.vhd
  C:/Users/guill/Desktop/Practica7.xpr/Practica7/Practica7.srcs/sources_1/imports/new/unidad_control.vhd
  C:/Users/guill/Desktop/Practica7.xpr/Practica7/Practica7.srcs/sources_1/imports/Martes12/caca/mux_16_entradas.vhd
  C:/Users/guill/Desktop/Practica7.xpr/Practica7/Practica7.srcs/sources_1/imports/UART/kcuart_tx.vhd
  C:/Users/guill/Desktop/Practica7.xpr/Practica7/Practica7.srcs/sources_1/imports/Martes12/caca/kcpsm3.vhd
  C:/Users/guill/Desktop/Practica7.xpr/Practica7/Practica7.srcs/sources_1/imports/Martes12/caca/bin_to_hex.vhd
  C:/Users/guill/Desktop/Practica7.xpr/Practica7/Practica7.srcs/sources_1/imports/Martes12/caca/biestable_D_1_bit.vhd
  C:/Users/guill/Desktop/Practica7.xpr/Practica7/Practica7.srcs/sources_1/imports/Martes12/caca/biestable_D.vhd
  C:/Users/guill/Desktop/Practica7.xpr/Practica7/Practica7.srcs/sources_1/imports/UART/bbfifo_16x8.vhd
  C:/Users/guill/Desktop/Practica7.xpr/Practica7/Practica7.srcs/sources_1/imports/new/mux_2_entradas.vhd
  C:/Users/guill/Desktop/Practica7.xpr/Practica7/Practica7.srcs/sources_1/imports/Picocode/picocode_s7.vhd
  C:/Users/guill/Desktop/Practica7.xpr/Practica7/Practica7.srcs/sources_1/imports/UART/uart_tx.vhd
  C:/Users/guill/Desktop/Practica7.xpr/Practica7/Practica7.srcs/sources_1/imports/Martes12/caca/selec_16_salidas_con_reg_y_mem_esc_lect.vhd
  C:/Users/guill/Desktop/Practica7.xpr/Practica7/Practica7.srcs/sources_1/imports/Martes12/caca/selec_16_entradas_con_reg_y_bypass.vhd
  C:/Users/guill/Desktop/Practica7.xpr/Practica7/Practica7.srcs/sources_1/imports/Martes12/caca/picoblaze3_empotrado_s7.vhd
  C:/Users/guill/Desktop/Practica7.xpr/Practica7/Practica7.srcs/sources_1/imports/new/periferico_complejo.vhd
  C:/Users/guill/Desktop/Practica7.xpr/Practica7/Practica7.srcs/sources_1/imports/Martes12/caca/Generador_CE_1KHz.vhd
  C:/Users/guill/Desktop/Practica7.xpr/Practica7/Practica7.srcs/sources_1/imports/Martes12/Practica5/pratica5.xpr/pratica5/pratica5.srcs/sources_1/new/FD8C3.vhd
  C:/Users/guill/Desktop/Practica7.xpr/Practica7/Practica7.srcs/sources_1/imports/Downloads/dual_port_dedicated_bram_sync_read.vhd
  C:/Users/guill/Desktop/Practica7.xpr/Practica7/Practica7.srcs/sources_1/imports/UART/generador_baudios.vhd
  C:/Users/guill/Desktop/Practica7.xpr/Practica7/Practica7.srcs/sources_1/imports/Martes12/Practica5/pratica5.xpr/pratica5/pratica5.srcs/sources_1/new/sistema_entero.vhd
}
synth_design -top sistema_entero -part xc7a100tcsg324-1
write_checkpoint -noxdef sistema_entero.dcp
catch { report_utilization -file sistema_entero_utilization_synth.rpt -pb sistema_entero_utilization_synth.pb }
